---
title: "All Seasons Prediction App"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
setwd("C:/Users/steph/Dropbox/Business University Science/Personal Portfolio/WIP/All_Seasons_Fund_WIP")
library(flexdashboard)
library(pacman)

pacman::p_load(
  # App
  "flexdashboard",
  "shiny",
  "shinyjs",
  "shinyWidgets",
  
  # Core
  "tidyquant",
  "tidyverse",
  "timetk",
  "tidyr",
  "tibble",
  "dplyr",
  "furrr", 
  "purrr",
  "dplyr",
  "glue",
  "forcats",
  "stringr",
  
  # Visualizations
  "plotly",
  "highcharter",
  "correlationfunnel",
  
  # Modeling
  "parsnip"
)

# Scripts
# source("../01_Scripts_Flex/wealth_index.R")
source("01_Scripts_Flex/wealth_index.R")

```

Column {.sidebar}
-----------------------------------------------------------------------

Please enter the stocks and weights you would like to evaluate

```{r}
# 
useShinyjs(rmd = TRUE)

# First Portfolio Input
fluidRow( #creates the input row
  column(6, #creates a column with length 6
         textInput(inputId = "stock1", 
                   label = "Stock 1", 
                   value = "VTI")), #creates the text input field
  column(5,
         numericInput("w1", "Portf. %", 30,
                      min = 1, max = 100))
)

# Second Portfolio Input
fluidRow(
  column(6,
         textInput("stock2", "Stock 2", "TLT")),
  column(5,
         numericInput("w2", "Portf. %", 40,
                      min = 1, max = 100))
)

# Third Portfolio Input
fluidRow(
  column(6,
         textInput("stock3", "Stock 3", "IEF")),
  column(5,
         numericInput("w3", "Portf. %", 15,
                      min = 1, max = 100))
)

# Fourth Portfolio Input
fluidRow(
  column(6,
         textInput("stock4", "Stock 4", "GLD")),
  column(5,
         numericInput("w4", "Portf. %", 7.5,
                      min = 1, max = 100))
)

# Fifth Portfolio Input
fluidRow(
  column(6,
         textInput("stock5", "Stock 5", "DBC")),
  column(5,
         numericInput("w5", "Portf. %", 7.5,
                      min = 1, max = 100))
)

# Portfolio Rebalance Interval
fluidRow(
  column(6,
         selectInput("rebalance", "Rebalance Frequency",
                     c("Yearly" = "years",
                       "Monthly" = "months",
                       "Weekly" = "weeks")))
)


# Benchmark Portfolio Input
fluidRow(
  column(10,
         textInput("bench_stock", "Benchmark Stock", "SPY"))
)

# User input Start Date
fluidRow(
  column(7,
         dateInput("start_date",
                   "Starting Date",
                   "2006-02-01",
                   format = "yyyy-mm-dd"))
)

# User Input End Date
fluidRow(
  column(7,
         dateInput("end_date",
                   "End Date",
                   today(),
                   format = "yyyy-mm-dd"))
)


hr()
br()

# Submit button
actionButton(inputId = "submit", 
             label = "Submit", 
             icon = icon(name = "piggy-bank",
                         lib = "font-awesome")) # Enables use of eventReactive() functions
# Reset button
actionButton(inputId = "reset",
             label = "Reset",
             icon = icon("sync",
                         lib = "font-awesome")) 

# Once reset button is executed, original fields are recovered
observeEvent(eventExpr = input$reset,
             handlerExpr = {
               
               # recover text fields
               updateTextInput(session = session,
                                 inputId = "stock1",
                                 value = "VTI")
               updateTextInput(session = session,
                                 inputId = "stock2",
                                 value = "TLT")
               updateTextInput(session = session,
                                 inputId = "stock3",
                                 value = "IEF")
               updateTextInput(session = session,
                                 inputId = "stock4",
                                 value = "GLD")
               updateTextInput(session = session,
                                 inputId = "stock5",
                                 value = "DBC")
               # Recover percent fields
               updateNumericInput(session = session,
                                  inputId = "w1",
                                  value = 30)
               updateNumericInput(session = session,
                                  inputId = "w2",
                                  value = 40)
              updateNumericInput(session = session,
                                  inputId = "w3",
                                  value = 15)
              updateNumericInput(session = session,
                                  inputId = "w4",
                                  value = 7.5)
              updateNumericInput(session = session,
                                  inputId = "w5",
                                  value = 7.5)
              
              delay(ms = 500, expr = {
                click(id = "submit")
              })
              
             })

```


```{r}
# Wealth Index based on portfolio returns
portfolio_returns <- eventReactive(input$submit, {
  
  symbols <- c(input$stock1, 
               input$stock2,
               input$stock3,
               input$stock4,
               input$stock5)
  
  end <- input$end_date
  start <- input$start_date
  
  w <- c(input$w1/100,
         input$w2/100,
         input$w3/100,
         input$w4/100,
         input$w5/100)
  
  wts_tbl <- tibble(symbols, w)
  
# All seasons portfolio ----
all_seasons_data <- multi_asset_price_portfolio(symbols, end, start, wts_tbl) %>% 
  multi_asset_return_portfolio(period = "monthly") %>% 
  wealth_index(wts_tbl = wts_tbl, name_portfolio = "test portfolio")

# Start Date of all seasons portfolio
min_date <- all_seasons_data %>%   
  summarise(min_date = min(date), 
            max_date = max(date)) %>% 
  pull(min_date)

# S&P500 portfolio ----
sp500_data <- multi_asset_price_portfolio(symbols = input$bench_stock, 
                                          end, 
                                          start = min_date, 
                                          wts_tbl) %>% 
  multi_asset_return_portfolio(period = "monthly") %>% 
  wealth_index(wts_tbl = wts_tbl, name_portfolio = input$bench_stock)

# Combine data
bind_portfolio(all_seasons_data, sp500_data) 
}, 

# Renders on load
ignoreNULL = FALSE
)

# Asset returns
portfolio_prices <- eventReactive(eventExpr = input$submit,
                                  valueExpr = {
                                      symbols <- c(input$stock1, 
                                                   input$stock2,
                                                   input$stock3,
                                                   input$stock4,
                                                   input$stock5)
                                      
                                      end     <- input$end_date
                                      start   <- input$start_date
                                      
                                      w       <- c(input$w1/100,
                                             input$w2/100,
                                             input$w3/100,
                                             input$w4/100,
                                             input$w5/100)
                                      
                                      wts_tbl <- tibble(symbols, w)
      
                                      # Returns by ticker
                                      all_seasons_data <- multi_asset_price_portfolio(symbols, end, start, wts_tbl) %>% 
                                        multi_asset_return_portfolio(period = "monthly")
                                  })

# Setting up rolling sd by window 
port_rolling_sd_tq <- eventReactive(eventExpr = input$submit,
                                    valueExpr = {
                                      
                                      portfolio_prices <- portfolio_prices()
                                      # Portfolio returns based on weighting
                                      portfolio_returns_tq_rebalance <- portfolio_prices %>% 
                                        group_by(symbol) %>% 
                                        tq_portfolio(assets_col = symbol,
                                                     returns_col = returns,
                                                     weights = w,
                                                     col_rename = "returns",
                                                     rebalance_on = "months") #input$rebalance ----
                                      
                                      # Portfolio rolling sd based on user specified window
                                      portfolio_returns_tq_rebalance %>% 
                                        tq_mutate(mutate_fun = rollapply,
                                                  width = 24,   #input$window ----
                                                  FUN = sd,
                                                  col_rename = ("rolling_sd")) %>%  
                                        na.omit() %>% 
                                        select(date, rolling_sd)
                                  })



```


Column {.tabset .tabset-fade data-width=650}
-----------------------------------------------------------------------

### Portfolio vs Benchmark (Plotly)

```{r}
renderPlotly({
  (portfolio_returns() %>% 
    mutate(portfolio = as.factor(portfolio) %>% fct_reorder(investment.growth),
           label_text = str_glue("Portfolio: {str_to_title(portfolio)}
                                 Investment: {scales::dollar(investment.growth, accuracy = 1)}
                                 Growth %: {scales::percent(portfolio.wealthindex - 1, accuracy = 0.01)}")) %>% 
    ggplot(aes(x = date, y = investment.growth, col = portfolio)) +
    geom_point(aes(text = label_text), size = 0.1) + #Must indicate label_text for tooltip to showup 
    geom_line() + 
    
    # Addition of Global Financial Crisis vertical line in Sept 2008
    geom_vline(xintercept = as.numeric(as.Date("2008-09-01")), linetype = "dotted", color = "red", size = 1.5) +
    annotate("text", x =  as.Date("2008-09-01") + 1200, y = 23000, label = "2008 Financial Crisis", color = "red") + 

    scale_color_tq() + 
    scale_y_continuous(labels = scales::dollar_format()) + 
    labs(title = "Portfolio vs Benchmark (SP500)",
         x = "",
         y = "")) %>%  
  
    ggplotly(tooltip = "text") #workaround issue on ggplotly; add parenthsis in front of ggplot
})
```


### Rolling Standard Deviation (Highcharter)

```{r}
renderHighchart({
  
  port_rolling_sd_hc <- port_rolling_sd_tq() %>% 
    tk_xts(date_col = date) %>% 
    round(., 4) * 100
  
  highchart(type = "stock") %>% 
    hc_title(text = "All Seasons Rolling Volatility") %>% 
    hc_yAxis(title = list(text = "Volatility"),
             labels = list(format = "{value}%"),
             opposite = FALSE) %>% 
    hc_add_series(port_rolling_sd_hc,
                  name = "Portfolio Volatility",
                  color = palette_light()[[1]]) %>% 
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE) %>% 
    hc_exporting(enabled = TRUE)
  
  
  
  
})
```



Column {data-width=350}
-----------------------------------------------------------------------

### Tickers Used in First Portfolio

```{r}

first_portfolio <- eventReactive(input$submit, {

  symbols <- c(input$stock1,
               input$stock2,
               input$stock3,
               input$stock4,
               input$stock5)

  end <- input$end_date
  start <- input$start_date

  w <- c(input$w1/100,
         input$w2/100,
         input$w3/100,
         input$w4/100,
         input$w5/100)

  wts_tbl <- tibble(symbols, w)

  format_table(symbols, w)
},

# Renders on load
ignoreNULL = FALSE
)

# Render and output to the UI
output$first_port <- renderTable(first_portfolio())
tableOutput("first_port")

```

### Tickers and Weighting Used in Second Portfolio

```{r}
second_portfolio <- eventReactive(input$submit, {
  
  symbols <- input$bench_stock
  
  w <- 1
  
  format_table(symbols, w)
},

# Renders on load
ignoreNULL = FALSE)

# Render and output to the UI
output$second_port <- renderTable(second_portfolio())
tableOutput("second_port")

```

